config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'login' => 'access#login', as: :login

  resources :users, param: :username, only: [:show] do
    resources :posts, param: :title,
                      only: [:show, :new, :create, :edit, :update, :destroy]
  end

  resources :comments, only: [:create, :destroy]

  match ':controller(/:action(/:id))', via: [:get, :post]

end

app/models/category.rb
# Model class for a post category
class Category < ActiveRecord::Base
  has_many :posts
  belongs_to :parent_category, class_name: 'Category',
                               foreign_key: 'parent_category_id'
  has_many :subcategories, class_name: 'Category',
                           foreign_key: 'parent_category_id'

  validates :name,
            presence: true,
            uniqueness: true

  scope :sorted, -> { order('categories.name ASC') }
end

app/models/comment.rb
# Model class for a post comment
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/models/post.rb
# Model class for a blog post
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments

  validates :title, :content,
            presence: true
  validates :title, uniqueness: {
    scope: :user_id,
    message: 'You can\'t have two posts with the same name'
  }

  def to_param
    title
  end
end

app/models/user.rb
# Model class for a blog user
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts
  has_many :comments

  validates :username, :password, :email, :first_name, :last_name,
            presence: true
  validates :username, :email,
            uniqueness: true

  def to_param
    username
  end
end

app/controllers/access_controller.rb
# Controller that handles user authentication
class AccessController < ApplicationController
  def login
  end

  def attempt_login
    user = User.find_by_username(params[:username])
    authorized_user = user.authenticate(params[:password]) if user
    if authorized_user
      session[:username] = authorized_user.username
      session[:user_id] = authorized_user.id
      redirect_to(controller: 'users', action: 'show',
                  username: authorized_user.username)
    else
      flash[:error] = 'Invalid username/password combination.'
      redirect_to(action: 'login')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def user_id_from_session
    session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = user_id_from_session

    begin
      @comment.save!(comment_params)
    rescue ActiveRecord::ActiveRecordError
      redirect_to_show_post_with_error_message('There was an error saving this comment. Did you provide the content?')
    rescue StandardError
      redirect_to_show_post_with_error_message('There was an error saving this comment. Try again later.')
    else
      redirect_to(user_post_path(@comment.post.user, @comment.post))
    end
  end

  def destroy
    comment = Comment.find(comment_id_from_params)
    comment.destroy
    redirect_to(user_post_path(comment.post.user, comment.post))
  end

  private

  def post_id_from_params
    params[:comment][:post_id]
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end

  def comment_id_from_params
    params[:id]
  end

  def redirect_to_show_post_with_error_message(error_message)
    @post = Post.find(post_id_from_params)
    flash[:error] = error_message
    redirect_to(user_post_path(@post.user, @post)) && return
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @comment = Comment.new
    required_post
  end

  def new
    @user = User.find(user_id_from_session)
    @post = Post.new
    @categories = Category.sorted
  end

  def create
    @user = User.find(user_id_from_session)

    begin
      @post = @user.posts.create!(post_params)
    rescue ActiveRecord::ActiveRecordError
      redirect_to_new_with_error_message('There was an error saving this post. Check if all the fields are filled out.')
    rescue StandardError
      redirect_to_new_with_error_message('There was an error saving this post. Try again later.')
    else
      redirect_to(user_post_path(@post.user, @post))
    end
  end

  def edit
    required_post
    @categories = Category.sorted
  end

  def update
    @post = User.find(user_id_from_session).posts.find_by_title(params[:title])

    begin
      @post.update_attributes!(post_params)
    rescue ActiveRecord::ActiveRecordError
      redirect_to_edit_with_error_message('There was an error updating this post. Check if all the fields are filled out.')
    rescue ActiveRecord::RecordInvalid
      redirect_to_edit_with_error_message('There was an error updating this post. Check if all the fields are filled out.')
    rescue StandardError
      redirect_to_edit_with_error_message('There was an error updating this post. Try again later.')
    else
      redirect_to(user_post_path(@post.user, @post))
    end
  end

  def destroy
    required_post.destroy
    redirect_to(user_path(@user))
  end

  private

  def redirect_to_new_with_error_message(error_message)
    flash[:error] = error_message
    redirect_to(new_user_post_path(@user)) && return
  end

  def redirect_to_edit_with_error_message(error_message)
    flash[:error] = error_message
    redirect_to(edit_user_post_path(@post.user,
                                    title: params[:title])) && return
  end

  def username_from_params
    params[:user_username]
  end

  def title_from_params
    params[:title]
  end

  def required_post
    @user = User.find_by_username(username_from_params)
    @post = @user.posts.find_by_title(title_from_params)
  end

  def post_params
    params.require(:post).permit(:title, :content, :category_id)
  end
end

app/controllers/users_controller.rb
# Controller that handles user CRUD operations
class UsersController < ApplicationController
  def show
    @user = User.find_by_username(params[:username])
    @posts = @user.posts
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/login.html.haml
%div
  = form_tag action: 'attempt_login' do
    %table
      %tr
        %td
          = label_tag(:username)
        %td
          = text_field_tag(:username)
      %tr
        %td
          = label_tag(:password)
        %td
          = password_field_tag(:password)
      %tr
        %td
          &nbsp;
        %td
          = submit_tag('Log in')

app/views/home/index.html.haml
%header
  %h1 jabs
  =link_to('Login', login_url)
%p Jabs stands for 'just another blog site'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title jabs
    = stylesheet_link_tag    'application',
                             media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if !flash[:error].blank?
      .alert.alert-error
      = flash[:error]
    .container-fluid
      .row
        .span9
          = yield

app/views/posts/_form.html.haml
= f.label(:title, 'Title')
= f.text_field(:title)
%br
= f.label(:content, 'Content')
= f.text_area(:content)
%br
= f.label(:category, 'Category')
= f.select(:category_id, @categories.map { |c| [c.name, c.id] })
%br

app/views/posts/edit.html.haml
%h1 Edit this post

= form_for([@user, @post]) do |f|
  = render(partial: "form", locals: {f: f})
  = f.submit('Update Post')

app/views/posts/new.html.haml
%h1 Write a new post

= form_for([@user, @post]) do |f|
  = render(partial: "form", locals: {f: f})
  = f.submit('Create Post')

app/views/posts/show.html.haml
.post
  %h1= @post.title
  %p= @post.content
%hr
.comment_form
  = form_for(@comment) do |f|
    = f.text_area(:content)
    = f.hidden_field(:post_id, value: @post.id)
    %br
    = f.submit('Comment')
%hr
.comments
  - @post.comments.each do |comment|
    .comment
      %h5= comment.user.username
      %p= comment.content
    .comment_actions
      = link_to 'Delete', comment_path(comment), method: :delete,
                data: { confirm: 'Are you sure you want to delete this comment?'} if session[:user_id] == comment.user.id
    %br

app/views/users/show.html.haml
%header
  %h2
    "#{@user.username}'s Blog"
  = link_to '#' do
    Edit profile
  %br
  = link_to '#' do
    Logout
  %br
  = link_to new_user_post_path(@user.username) do
    New post
  %br
  %hr
  %br

.posts
  - @posts.each do |post|
    .post_preview
      %h3= post.title
      %p= post.content
    .post_actions
      = link_to 'Show', user_post_path(user_username: post.user, title: post)
      = link_to 'Edit', edit_user_post_path(user_username: post.user, title: post)
      = link_to 'Delete', user_post_path(user_username: post.user, title: post),
                method: :delete,
                data: { confirm: 'Are you sure you want to delete this post?' } if session[:user_id] == post.user.id